version: '3.4'

services:
  crazyivan:
    image: aostreetart/crazyivan:v2
    volumes:
      - ${SSL_BASE_DIR}:/ssl
    network_mode: "host"
    environment:
      - IVAN_PROD_HTTP_HOST=${AESEL_DOMAIN}
      - IVAN_PROD_CLUSTER=demo
      - IVAN_PROD_ADRESTIA_CACHE_LOAD=false
      - IVAN_PROD_TRANSACTION_SECURITY_SSL_ENABLED=true
      - IVAN_PROD_TRANSACTION_SECURITY_AUTH_TYPE=single
      - IVAN_PROD_TRANSACTION_SECURITY_AUTH_USER=${IVAN_UN}
      - IVAN_PROD_TRANSACTION_SECURITY_AUTH_PASSWORD=${IVAN_PW}
      - IVAN_PROD_TRANSACTION_SECURITY_HASH_PASSWORD=${IVAN_HASH_PW}
      - IVAN_PROD_EVENT_SECURITY_AES_ENABLED=true
      - IVAN_PROD_DEMO_EVENT_SECURITY_IN_AES_PASSWORD=${IVAN_IN_AES_PASSWORD}
      - IVAN_PROD_DEMO_EVENT_SECURITY_IN_AES_SALT=${IVAN_IN_AES_SALT}
      - IVAN_PROD_DEMO_EVENT_SECURITY_IN_AES_KEY=${IVAN_IN_AES_KEY}
      - IVAN_PROD_DEMO_EVENT_SECURITY_IN_AES_IV=${IVAN_IN_AES_IV}
      - IVAN_PROD_DEMO_EVENT_SECURITY_OUT_AES_PASSWORD=${IVAN_OUT_AES_PASSWORD}
      - IVAN_PROD_DEMO_EVENT_SECURITY_OUT_AES_SALT=${IVAN_OUT_AES_SALT}
      - IVAN_PROD_DEMO_EVENT_SECURITY_OUT_AES_KEY=${IVAN_OUT_AES_KEY}
      - IVAN_PROD_DEMO_EVENT_SECURITY_OUT_AES_IV=${IVAN_OUT_AES_IV}
      - IVAN_PROD_DEMO_EVENT_SECURITY_REGISTRATION_AES_PASSWORD=${IVAN_REGISTRATION_AES_PASSWORD}
      - IVAN_PROD_DEMO_EVENT_SECURITY_REGISTRATION_AES_SALT=${IVAN_REGISTRATION_AES_SALT}
      - IVAN_PROD_DEMO_EVENT_SECURITY_REGISTRATION_AES_KEY=${IVAN_REGISTRATION_AES_KEY}
      - IVAN_PROD_DEMO_EVENT_SECURITY_REGISTRATION_AES_IV=${IVAN_REGISTRATION_AES_IV}
      - IVAN_PROD_NEO4J=neo4j://${NEO4J_USER}:${NEO4J_PW}@${AESEL_DOMAIN}:7687
      - IVAN_PROD_NEO4J_SSL_CA_FILE=/ssl/ca.crt
  clyman:
    image: aostreetart/clyman:v2
    volumes:
      - ${SSL_BASE_DIR}:/ssl
    network_mode: "host"
    environment:
      - CLYMAN_PROD_CLUSTER=demo
      - CLYMAN_PROD_MONGO=mongodb://${MONGO_INIT_USER}:${MONGO_INIT_PW}@${AESEL_DOMAIN}:27017/
      - CLYMAN_PROD_MONGO_AUTH_UN=${MONGO_CLYMAN_USER}
      - CLYMAN_PROD_MONGO_AUTH_PW=${MONGO_CLYMAN_PW}
      - CLYMAN_PROD_MONGO_SSL_ACTIVE=true
      - CLYMAN_PROD_MONGO_SSL_CA_FILE=/ssl/ca.crt
      - CLYMAN_PROD_TRANSACTION_SECURITY_SSL_ENABLED=true
      - CLYMAN_PROD_TRANSACTION_SECURITY_AUTH_TYPE=single
      - CLYMAN_PROD_TRANSACTION_SECURITY_AUTH_USER=${CLYMAN_UN}
      - CLYMAN_PROD_TRANSACTION_SECURITY_AUTH_PASSWORD=${CLYMAN_PW}
      - CLYMAN_PROD_TRANSACTION_SECURITY_HASH_PASSWORD=${CLYMAN_HASH_PW}
      - CLYMAN_PROD_EVENT_SECURITY_AES_ENABLED=true
      - CLYMAN_PROD_DEMO_EVENT_SECURITY_IN_AES_PASSWORD=${CLYMAN_IN_AES_PASSWORD}
      - CLYMAN_PROD_DEMO_EVENT_SECURITY_IN_AES_SALT=${CLYMAN_IN_AES_SALT}
      - CLYMAN_PROD_DEMO_EVENT_SECURITY_IN_AES_KEY=${CLYMAN_IN_AES_KEY}
      - CLYMAN_PROD_DEMO_EVENT_SECURITY_IN_AES_IV=${CLYMAN_IN_AES_IV}
      - CLYMAN_PROD_DEMO_EVENT_SECURITY_OUT_AES_PASSWORD=${CLYMAN_OUT_AES_PASSWORD}
      - CLYMAN_PROD_DEMO_EVENT_SECURITY_OUT_AES_SALT=${CLYMAN_OUT_AES_SALT}
      - CLYMAN_PROD_DEMO_EVENT_SECURITY_OUT_AES_KEY=${CLYMAN_OUT_AES_KEY}
      - CLYMAN_PROD_DEMO_EVENT_SECURITY_OUT_AES_IV=${CLYMAN_OUT_AES_IV}
      - CLYMAN_PROD_HTTP_HOST=${AESEL_DOMAIN}
      - CLYMAN_PROD_EVENT_DESTINATION_HOST=${NETWORK_INTERFACE_ADDRESS}
      - CLYMAN_PROD_EVENT_DESTINATION_PORT=8764
